export const screens = {
    HELLO: 'Hello',
    MAIN: 'Main',
    ONBOARDING: 'Onboarding',
    SIGNUP: 'Signup',
    SIGNIN: 'Signin',
    HOWTOLOGIN: 'HowToLogin',
    FILLPROFILE: 'FillProfile',

    HOMESTACK: 'HomeStack',
    CARTSTACK: 'CartStack',
    ORDERSTACK: 'OrderStack',
    WALLETSTACK: 'WalletStack',
    PROFILESTACK: 'ProfileStack',
    HOME: 'Home',
    CART: 'Cart',
    ORDER: 'Order',
    WALLET: 'Wallet',
    PROFILE: 'Profile',
    SEARCH: 'Search',
}